services:

  db:
    image: mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: argos
    networks:
      - network
    hostname: db
    volumes:
      - argos-db:/var/lib/mysql


  app:
    build: .
    working_dir: /usr/src/app
    ports:
      - '8080:8080'
    depends_on:
      - db
    networks:
      - network
    hostname: app
    environment:
      - DB_URL=db
    volumes:
      - ./src/config/systemConfig.json:/usr/src/app/src/config/systemConfig.json

  nginx:
    image: nginx:latest
    ports:
      - '80:80'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - network    

networks:
  network: {}

volumes:
  argos-db: