services:

  db:
    image: mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: argos
    networks:
      - network
    hostname: db
    volumes:
      - argos-db:/var/lib/mysql


  app:
    build: .
    ports:
      - '8080:8080'
    depends_on:
      - db
    networks:
      - network
    environment:
      - DB_URL=db

networks:
  network: {}

volumes:
  argos-db: